---
extends: default

rules:
  comments:
    require-starting-space: false
    min-spaces-from-content: 1
  comments-indentation: disable  # don't bother me with this rule

#  line-length: disable # disable line-length checks entirely
  line-length:
    max: 100

  # accept both     key:
  #                   - item
  #
  # and             key:
  #                 - item
  indentation:
    indent-sequences: whatever
