---
- name: Sanity checks
  assert:
    that:
    - user_info is defined
    - password_for_all is defined
    - password_for_all | length >= 8
    fail_msg: "Undefined variables or password does not meet complexity requirements"
    success_msg: "All required variables are defined"

- name: Create AD groups
  win_domain_group:
    name: "{{ item.group_name }}"
    scope: "{{ item.group_scope }}"
  loop: "{{ user_info.groups }}"
  ignore_errors: true

- name: Create AD users (no_log to prevent passwords being printed)
  win_domain_user:
    name: "{{ item.user_name }}"
    firstname: "{{ item.firstname }}"
    surname: "{{ item.surname }}"
    password: "{{ item.password }}"
    state: present
    groups: "{{ item.group }}"
  loop: "{{ user_info.users }}"
  ignore_errors: true
  no_log: true # prevent passwords from being printed
